name: MF9155_course

channels:
    - r
    - bioconda
    - conda-forge

dependencies:
    - r-base=3.6.1
    - r-essentials=3.6.0
    - r-biocmanager=1.30.4
    - r-pheatmap=1.0.12
    - r-cluster=2.0.8
    - bioconductor-consensusclusterplus=1.50.0
    - r-rcolorbrewer=1.1_2
    - bioconductor-limma=3.42.0
    - bioconductor-edger=3.28.0
    - bioconductor-deseq2=1.26.0
    - r-glmnet=2.0_16
    - r-randomforestsrc=2.9.2
    - r-hmisc=4.2_0
    - r-psych=1.8.12
    - bioconductor-biobase=2.46.0
    - bioconductor-genefilter=1.68.0
    - r-venndiagram=1.6.20
    - bioconductor-org.hs.eg.db=3.10.0
    - bioconductor-hgu133plus2.db=3.2.3
    - bioconductor-annotationdbi=1.48.0
    - bioconductor-biomart=2.42.0
    - bioconductor-geoquery=2.54.0
    - bioconductor-biostrings=2.54.0
    - bioconductor-gcrma=2.58.0
    - bioconductor-affy=1.64.0
    - bioconductor-genomicranges=1.38.0
    - bioconductor-gviz=1.30.0
    - bioconductor-rtracklayer=1.46.0
    - r-seqinr=3.6_1
    - r-fitdistrplus=1.0_14
    - r-tidyverse=1.2.1
    - r-ggplot2=3.1.1
    - r-reshape2=1.4.3
    - r-stringr=1.4.0
    - r-data.table=1.12.2
    - r-optparse=1.6.4
    - r-rjson=0.2.20
    - r-yaml=2.2.0
    - r-dplr=1.7.0
    - r-readr=1.3.1
    - r-logging=0.10_108
    - r-microbenchmark=1.4_7
    - r-islr=1.2
    - r-devtools=2.0.2
